title: Abrar Mudhir
email: abrarmudhir@outlook.com
description: >-
  Profile Page
baseurl: ""
url: "https://abrarmudhir.github.io/"
analytics: true
github_url:  https://github.com/abrarmudhir
linkedin_url: https://www.linkedin.com/in/abrar-mudhir/

markdown: kramdown
kramdown:
  syntax_highlighter: rouge

# Build settings
theme: just-the-docs
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-head
  - jekyll-include-cache # for using include_relative

defaults:
  -
    scope:
      type: posts
      path: "_posts/experience"
    values:
      isPost: true
      layout: post
      category: experience
  -
    scope:
      type: posts
      path: "_posts/organisations"
    values:
      isPost: true
      layout: post
      category: organisations
  -
    scope:
      type: posts
      path: "_posts/qanda"
    values:
      isPost: true
      layout: post
      category: qanda
  -
    scope:
      type: pages
      path: _pages
    values:
      isPost: false
      layout: default

permalink: /:categories/:year/:month/:day/:title/

include:
  - _pages

exclude:
  - .idea
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

port: 4001

favicon_ico: /assets/img/icons/favicon.ico

search_enabled: true
